// REWRITING DATA TABLE FROM SCRATCH - SHADCN & CLAUDE CAN'T BE TRUSTED
// FEATURES:
// - LIST ALL REPORTS IN DATABASE
// - INCLUDE COLUMNS: STATUS, ID, EMBARK ID, REASON, FILED AT (UTC), UPDATED AT (UTC), ROW ACTIONS
// - FOR COLUMNS INFER TYPES FROM DATA RETURN THEN OMIT UNNECESSARY OBJECT KEYS (NOT FROM DATA, FROM TYPES)
// - ROW ACTIONS: REVIEW REPORT, ISOLATE RAIDER, COPY REPORT, COPY EMBARK ID
// - STILL PASS COMPLETE REPORT DATA TO DUMP IT INTO COPY REPORT & ASSESSMENT DRAWER/DIALOG LATER (TABLE IS ABRIDGED)
// - SEARCH BY REPORT ID OR EMBARK ID (DETECT PATTERN, CONSIDER FUZZY DURING EMBARK ID PATTERN)
// - STATUS CHECKBOX FILTER (PENDING, UNDER REVIEW, APPROVED, REJECTED) DEFAULT PENDING & UNDER REVIEW
// - PAGINATION (SHOWING N-N of N REPORTS), ROWS PER PAGE SELECT, ARROWS, NO PAGE NUMBERS OR ELLIPSIS IT SERVES NO PURPOSE
// - OTHER THAN TRYING TO HIT SPECIFIC DATE RANGES, WHICH WOULD BE BETTER DONE WITH A DATE PICKER (SINGLE OR RANGED)

import { useQuery } from "@tanstack/react-query";
import { getReportsTableData } from "@/_server/serverFunctions";

export function ReportsTable() {
  const { data, isPending, isError } = useQuery({
    queryKey: ["reportsTable"],
    queryFn: getReportsTableData,
  });

  return (
    <div>
      <h1>Reports Table</h1>
    </div>
  );
}
